name: PyTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Install playwright
      run: playwright install

    - name: Install webkit dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            libwoff2dec1 \
            libvpx7 \
            libevent-2.1-7 \
            libopus0 \
            libgstallocators1.0-0 \
            libgstapp1.0-0 \
            libgstpbutils1.0-0 \
            libgstaudio1.0-0 \
            libgsttag1.0-0 \
            libgstvideo1.0-0 \
            libgstgl1.0-0 \
            libgstcodecparsers1.0-0 \
            libgstfft1.0-0 \
            libharfbuzz-icu0 \
            libhyphen0 \
            libmanette-0.2-0 \
            libflite1 \
            libflite-usenglish1 \
            libflite-cmu-grapheme-lang1 \
            libflite-cmu-grapheme-lex1

    - name: Run PyTest
      run: pytest --browser chromium --browser firefox --browser webkit
